### ISSUE TITLE
issues error with typescript

### ISSUE THREAD

**Issue by 799956381** [raychenfj/ion-multi-picker#1]
tsc --version   v2.0.2

error

TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/img/img.d.ts(24,14): Error TS1005: '=' exp
ected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/img/img.d.ts(24,20): Error TS1005: ';' exp
ected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/img/img.d.ts(25,14): Error TS1005: '=' exp
ected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/img/img.d.ts(25,21): Error TS1005: ';' exp
ected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/label/label.d.ts(11,14): Error TS1005: '='
 expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/label/label.d.ts(11,18): Error TS1005: ';'
 expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/menu/menu-toggle.d.ts(13,14): Error TS1005
: '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/menu/menu-toggle.d.ts(13,22): Error TS1005
: ';' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/option/option.d.ts(12,14): Error TS1005: '
=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/option/option.d.ts(12,18): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/range/range.d.ts(78,14): Error TS1005: '='
 expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/range/range.d.ts(78,19): Error TS1005: ';'
 expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/range/range.d.ts(79,14): Error TS1005: '='
 expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/range/range.d.ts(79,24): Error TS1005: ';'
 expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(40,14): Error TS1005: '
=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(40,18): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(40,20): Error TS1068: U
nexpected token. A constructor, method, accessor, or property was expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(41,31): Error TS1005: '
(' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(42,15): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(42,21): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(44,19): Error TS1005: '
,' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(44,25): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(44,31): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(45,25): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(45,31): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(46,24): Error TS1005: '
,' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(46,35): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(46,41): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(47,25): Error TS1005: '
,' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(47,31): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(47,37): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(48,17): Error TS1005: '
,' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(48,23): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(48,29): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(49,16): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(49,22): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(50,18): Error TS1005: '
;' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(50,24): Error TS1109: E
xpression expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/select/select.d.ts(51,1): Error TS1128: De
claration or statement expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/tabs/tab.d.ts(41,14): Error TS1005: '=' ex
pected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/tabs/tab.d.ts(41,19): Error TS1005: ';' ex
pected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(37,14): E
rror TS1005: '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(37,19): E
rror TS1005: ';' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(38,14): E
rror TS1005: '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(38,18): E
rror TS1005: ';' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(39,14): E
rror TS1005: '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(39,18): E
rror TS1005: ';' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(40,14): E
rror TS1005: '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts(40,17): E
rror TS1005: ';' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/navigation/view-controller.d.ts(48,14): Error TS1005:
 '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/navigation/view-controller.d.ts(48,18): Error TS1005:
 ';' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/navigation/view-controller.d.ts(49,14): Error TS1005:
 '=' expected.
TypeScript error: /node_modules/ion-multi-picker/
node_modules/ionic-angular/navigation/view-controller.d.ts(49,19): Error TS1005:
 ';' expected.

**Comment by raychenfj** [comment]
Thanks for the first issuse.
You know, I run tsc to complie before publishing to npm, but I never encounter this.

Can you provide more detail ? 
Like how you install this package ?  Do you install via npm ? It will be helpful if you can provide a minimal demo to reproduce this.

From you error log, I notice the directory structure is quite strange, node_modules nest node_modules. ionic-angular is offical ionic package, it really shouldn't nest in my package.

**Comment by m927259903** [comment]
hi there, how did you configure your tsconfig.json. i suspect a problem of tsconfig.json

**Comment by raychenfj** [comment]
Hi @799956381 ,
Haven't heard from you for a while.
My suggestions are:
* Check the package directory, it shouldn't contain node_modules.
* update your npm version to latest.
* reinstall the package.

I will close this issue. You can open a new one if you still have the same problem.
