### ISSUE TITLE
When value contains space, the display text is set to blank

### ISSUE THREAD

**Issue by inabhi9** [raychenfj/ion-multi-picker#17]

**Comment by raychenfj** [comment]
Hi @inabhi9 
Thanks for feedback, will take a look and let you know when I solve it.

**Comment by raychenfj** [comment]
Hi @inabhi9 
You can update to version 1.1.0 and then use the input attribute `separator` to change the charactor used to separate value from each column, by default it's space.
```
<ion-multi-picker id="separator" [(ngModel)]="sepVal" item-content [multiPickerColumns]="sepColumns" [separator]="'_'"></ion-multi-picker>
```

**Comment by inabhi9** [comment]
@raychenfj Thank you so much! (y)

**Comment by GRPS** [comment]
Thanks for the picker raychenfj it fits my needs perfectly. I have made a slight change to my multi-picker.js file as the separator wasn't being honoured.

`MultiPicker.prototype.updateText = function () {
        var _this = this;
        this._text = '';
        var values = this._value.toString().split(this.separator);
        this.multiPickerColumns.forEach(function (col, index) {
            var option = col.options.find(function (option) { return option.value.toString() === values[index]; });
            if (option) {
				_this._text += (index == 0?'':_this.separator) + option.text;
            }
        });
        this._text.trim();
    };`
