### ISSUE TITLE
请问可以升级一下依赖么

### ISSUE THREAD

**Issue by m927259903** [raychenfj/ion-multi-picker#2]
你好，朋友， 这款插件真的很好用， 解决了我的燃眉之急。在这里表示感谢。
今天升级rc2和angular2.1.1, 发现插件是基于rc0的，虽然使用没有什么问题，但还是想询问一下，可否升级一下依赖。
另外，我使用了Enum类型的值绑定 `ngModel` 传入会报错，发现这个插件只能传入字符串， 并不是特别方便， 希望改进一下。

**Comment by raychenfj** [comment]
@m927259903 
感谢提醒，没有问题
估计一星期内能发布个新版本，升级依赖和支持Enum
另外方便提供个Enum的用例么？ 方便我测试时参考

**Comment by m927259903** [comment]
Enum编译出来就是一个Object闭包，里面是一串键值对

**Comment by raychenfj** [comment]
@m927259903 
我已经升级版本到1.0.7
* 支持Ionic2 2.0.0-rc.2
* 支持了Enum类型
* 提供一个Util `convertEnumToColumn`方法根据Enum类型生成对应的Column，然后直接传入即可。

你可以测试一下，没问题我就关这个issue了

**Comment by raychenfj** [comment]
As @m927259903  Suggested, I update the dependency to support latest ionic2 version, and add new feature to support Enum type.

**Comment by m927259903** [comment]
Thanks. got you
