### ISSUE TITLE
Add md style/support for Android

### ISSUE THREAD

**Issue by Fdom92** [raychenfj/ion-multi-picker#22]

**Comment by Fdom92** [comment]
Ok, i was looking into your project and i see that you have styles for ios, md and wp. I opened this cause i think your plugin it was only for ios like it shows here:

https://market.ionic.io/plugins/ionic_multi_picker :(

So you can close this issue.

**Comment by raychenfj** [comment]
Hi @Fdom92 

I submit this add-on two months ago, but have some problems to update it in the ionic market. 

So please find the latest version in NPM [https://www.npmjs.com/package/ion-multi-picker](https://www.npmjs.com/package/ion-multi-picker).
