### ISSUE TITLE
Changing separator does not affect text displaying selection

### ISSUE THREAD

**Issue by chanphillip** [raychenfj/ion-multi-picker#28]
After changing the separator, the string value of the model is affected, but the selected option is still showing space.

**Comment by chanphillip** [comment]
After playing around for awhile, I realized the separator is just for the string value.
I wonder if there can be a way to format the text to display.

**Comment by raychenfj** [comment]
Hi @chanphillip 
You can refer to Issue #17.
The separator only separates value, not text, that's the desired behavior for now.
Also, I'm considering use the separator to format the text as well in next version.

**Comment by chanphillip** [comment]
@raychenfj Got it.
It's an awesome plugin! Thanks!

**Comment by raychenfj** [comment]
Hi@chanphillip 
You can try version 1.1.1, should use the separator to separate text as well.
