### ISSUE TITLE
Get the data from the network

### ISSUE THREAD

**Issue by jun1362008** [raychenfj/ion-multi-picker#29]
Thank you so much for this demo.
Now I hope to get the data from the network and then update the columns, what should I do?

**Comment by raychenfj** [comment]
Hi @jun1362008
I suppose when you say 'network', you mean from a backend server right ? 

So you know, ionic2 is build upon angular2. Getting remote data is nothing special.
Basically,  in the ngOnInit of your page or component, you need to send http request to your backend server,  then in the callback, update your columns based on the response data.

Here is [angular2 http client](https://angular.io/docs/ts/latest/guide/server-communication.html)

**Comment by jun1362008** [comment]
Thank you for your answer.
But I want to update the columns with different async data. Such as the province, city, district, I want to get the async data when I change the columns.

**Comment by raychenfj** [comment]
@jun1362008 
Unfortunately, there is no way to get async data while you are interacting with the picker.
You have to initialize the columns at the very beginning then bind it to the picker.

However, I guess you can try the `parentVal` attribute, it can establish relation between each columns. When the parent column is changed, the child column will be changed as well.
