### ISSUE TITLE
Uncaught Error: Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by chanphillip** [raychenfj/ion-multi-picker#30]
Hi
Recently I've updated my ionic, angular and node to the latest versions. Everything was working properly except some minor issues from ionic or angular. This picker was working also.
Today when I tried re-installing older verions of ionic, angular and node. It compiles correctly but gives me this error message

> Uncaught Error: Unexpected value 'undefined' imported by the module 'AppModule'

Then I tried re-installing all the latest versions, it still gave me the same message.

Here is my app.module.ts
```
import { NgModule, ErrorHandler } from '@angular/core';
import { HttpModule } from '@angular/http';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { NgCalendarModule } from 'ionic2-calendar';
import { MultiPickerModule } from 'ion-multi-picker';

import { HomePage } from '../pages/home/home';
...

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    ...
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    HttpModule,
    NgCalendarModule,
    MultiPickerModule,
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    ...
  ],
  providers: [
    [{ provide: ErrorHandler, useClass: IonicErrorHandler }],
    ...
  ]
})
export class AppModule {}
```

My ionic info
```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by raychenfj** [comment]
Hi @chanphillip,
Usually it's related to you dev enviorment and your version.
Here is similar issue #24 and #21 .

**Comment by bardhii** [comment]
Hi Chan,

i have the same issue and just wanted to report it, but you already did^^.
I think that the problem is that the metaDataResolver wont find the MultiPickerModule because its exported with a *. I'm not sure if the bug is in the module or in the metaDataResolver. 
Anyway....

I've changed the following and it worked again : 
in the file : node_modules/ion-multi-picker/dist/index.js

**export * from './module';** to **export {MultiPickerModule} from './module';**

cheers

bardh

**Comment by chanphillip** [comment]
Hi @bardhii 
It works again like a charm! Thanks!

@raychenfj I saw the two issues but I still couldn't fix it.
Removing this plugin my app works properly, so I wonder if this is a bug of this plugin.
Hope this helps the others.
