### ISSUE TITLE
Fail in RC4

### ISSUE THREAD

**Issue by Fdom92** [raychenfj/ion-multi-picker#32]
Hi @raychenfj, I just updated ionic to RC4 and im getting this error:

`Runtime Error
Unexpected value 'undefined' imported by the module 'AppModule'`

And i was searchin for the error when i commented this line on app.module:

`MultiPickerModule`

all works fine. Can you test it?

**Comment by bardhii** [comment]
Hi @Fdom92 see issue #30 which is 'closed'
regards

**Comment by fjulia** [comment]
Hi @raychenfj I also have problems with ionic RC4 update.
Unexpected value 'MultiPickerModule' imported by the module 'AppModule'

I've edited index.js and suggested in issue #30 but it does not solve the problem.

regards

**Comment by bardhii** [comment]
@fjulia just tested it with RC4 and the solution from #30. it works.. Could you provide some more information.. e.g. ionic info, error log from the console to see which component logs the error..

Regards
_________
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.9.2
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by fjulia** [comment]
I've done npm cache clean, removed node_modules/ and made a npm install.


At ionic serve build process it's all ok but on the browser console I get the following error:

`Uncaught Error: Unexpected value 'undefined' imported by the module 'AppModule'`

Then I edit index.js as suggested in #30, and the error I get is:

```
Uncaught Error: Unexpected value 'MultiPickerModule' imported by the module 'AppModule'
    at eval (/appPath/node_modules/@angular/compiler/src/metadata_resolver.js:379:31)
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/appPath/node_modules/@angular/compiler/src/metadata_resolver.js:364:49)
    at CompileMetadataResolver.loadNgModuleMetadata (/appPath/node_modules/@angular/compiler/src/metadata_resolver.js:329:29)
    at RuntimeCompiler._loadModules (/appPath/node_modules/@angular/compiler/src/runtime_compiler.js:116:41)
    at RuntimeCompiler._compileModuleAndComponents (/appPath/node_modules/@angular/compiler/src/runtime_compiler.js:86:35)
    at RuntimeCompiler.compileModuleAsync (/appPath/node_modules/@angular/compiler/src/runtime_compiler.js:76:21)
    at PlatformRef_._bootstrapModuleWithZone (/appPath/node_modules/@angular/core/src/application_ref.js:328:25)
    at PlatformRef_.bootstrapModule (/appPath/node_modules/@angular/core/src/application_ref.js:310:21)
    at eval `(/appPath/src/app/main.dev.ts:5:124)`
```

Regards,

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Debian Testing
Node Version: v6.9.2
Xcode version: null

**Comment by fjulia** [comment]
After setting ionic version back to 2.0.0-rc3 I have to do an npm cache clean, rm node_modules/ -r and npm install.

There is not enough doing an npm cache clean, npm install.
My dependencies in package.json are:
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "chart.js": "^2.3.0",
    "ion-multi-picker": "1.1.1",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-app-lib": "2.1.5",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "ng2-charts": "1.4.1",
    "ng2-cookies": "^1.0.3",
    "ng2-translate": "^3.1.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"

Thanks

**Comment by chanphillip** [comment]
I got the same issue with RC4.
It's fine when  running `ionic build android` but `ionic build android --prod`

**Comment by raychenfj** [comment]
Thanks everyone.
I will update it to RC4 as soon as I can.

**Comment by Fdom92** [comment]
thanks @raychenfj :)

**Comment by raychenfj** [comment]
Hi all,
version 1.1.2 is was published, support RC4 and should solve this issue as well.
But after updating to RC4, the transition when you click an option sometimes is not that smooth, will keep looking into it.
