### ISSUE TITLE
Label color is overridden

### ISSUE THREAD

**Issue by moldstadt** [raychenfj/ion-multi-picker#34]
If I set the label color for the multi picker (e.g., color="primary"), it is ignored and set to #999.

**Comment by raychenfj** [comment]
Hi @moldstadt 
I would like to help, but can you provide more info ? like your css  or the your code snippet ?

**Comment by moldstadt** [comment]
Hi @raychenfj,

If you take the first example in the readme and modify the template as follows:

    <ion-item>
        <ion-label color="primary">Simple Picker</ion-label>
        <ion-multi-picker item-content [multiPickerColumns]="simpleColumns"></ion-multi-picker>
    </ion-item>

The label color stays grey. Should be blue.
No css changes to default ionic theme.

**Comment by raychenfj** [comment]
@moldstadt 
Thanks, fixed in version 1.1.3.

**Comment by moldstadt** [comment]
Thanks @raychenfj.

**Comment by moldstadt** [comment]
Hi @raychenfj,

I can confirm that this is working as expected now. Thanks.
