### ISSUE TITLE
dont work with prod mode

### ISSUE THREAD

**Issue by HonLuk** [raychenfj/ion-multi-picker#39]
run well with `ionic build android` but dont work with `ionic build android --prod`,
error show EXCEPTION: No provider for t!
i dont know what is "t" means. becuase build with "prod";

  "ionic-angular": "^2.0.0",
"@ionic/app-scripts": "1.1.3",

**Comment by danielehrhardt** [comment]
https://github.com/driftyco/ionic/issues/10684

**Comment by HonLuk** [comment]
@danielehrhardt i can build with prod and install to android device.every page work well but which use ion-multi-picker. cant push to page which used ion-multi-picker.

**Comment by danielehrhardt** [comment]
Des same here

**Comment by raychenfj** [comment]
Thanks
Every time ionic bump version, it will cause some backwards compatible issues 🙁
Will look into it

**Comment by danielehrhardt** [comment]
@raychenfj Awesome Thank you!!!

**Comment by HonLuk** [comment]
@raychenfj thanks! waiting for good news.

**Comment by raychenfj** [comment]
@HonLuk  @danielehrhardt

Hi guys,
Please try new release 1.2.0, should work

**Comment by HonLuk** [comment]
@raychenfj  well done!everything goes well. i use it for make a Chinese city pick. if u want i can send Chinese city.json for u.i think maybe many Chinese developer need it. thanks!!!

**Comment by raychenfj** [comment]
@HonLuk 
Cool! You can send it to my gmail, or event better send me a PR.
I always want a full copy of Chinese city data, but it's a shame I can't find a suitable format.

**Comment by HonLuk** [comment]
@raychenfj so sorry for send it so late.im buzy this week.and did not find you replied me.check your email.good day~!
