### ISSUE TITLE
remove/clean console.log

### ISSUE THREAD

**Issue by sijad** [raychenfj/ion-multi-picker#4]
Thanks for this.
but could you please remove or disable `console.log` and `console.debug` from code?

**Comment by m927259903** [comment]
:joy:

**Comment by raychenfj** [comment]
@sijad Sorry for the annoying debug info, it's gone now.
please update to version 1.0.7, it should support the latest Ionic2 2.0.0-rc.2 as well.

I will close this issue.

**Comment by sijad** [comment]
thanks @raychenfj
