### ISSUE TITLE
Ionic 2.2.0 - prod build error

### ISSUE THREAD

**Issue by danielehrhardt** [raychenfj/ion-multi-picker#40]
Have the Same Problem with 2.1.0 https://github.com/raychenfj/ion-multi-picker/issues/39.

And with 2.2.0 i got this issue:

![image](https://cloud.githubusercontent.com/assets/19570043/23729540/ba3cbc0c-0462-11e7-9aa0-5f5db8ef03bb.png)

`[23:44:04]  ngc started ... 
[23:44:08]  build prod failed: Error encountered resolving symbol values statically. Calling function 
            'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a 
            reference to an exported function, resolving symbol Injectable in 
            /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol 
            OpaqueToken in 
            /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving 
            symbol OpaqueToken in 
            /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/opaque_token.d.ts 
[23:44:08]  ionic-app-script task: "build" 
[23:44:08]  Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function 
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
            resolving symbol Injectable in 
            /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol 
            OpaqueToken in 
            /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving 
            symbol OpaqueToken in 
            /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/opaque_token.d.ts 
Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /bitrise/src/node_modules/ion-multi-picker/node_modules/@angular/core/src/di/opaque_token.d.ts`

**Comment by raychenfj** [comment]
Fixed in release 1.2.0
