### ISSUE TITLE
Request add more buttons with handle 

### ISSUE THREAD

**Issue by hbt272** [raychenfj/ion-multi-picker#41]
Hi,
I would like this component has an option about add custom button with custom handle data picked like this:
`<ion-multi-picker id="simple" item-content [multiPickerColumns]="columns" [(ngModel)]="data" selectOptions="options"></ion-multi-picker>`
And the options has this structor:
`options = {
  		buttons: [
       {
         text: 'button1',
         handler: () => { console.log('do some thing');}
       },
       {
         text: 'buttob2',
         handler: (data) => { console.log('data');}
       }
     ]
  	}`

I see in your code have `pickerOptions.buttons` in the open() funtion.
I think you can append more button here!
Hope this feature success! Thanks.

**Comment by raychenfj** [comment]
@hbt272 

Thanks for feedback, will take a look 🙃

**Comment by raychenfj** [comment]
@hbt272 

Yes, technically this is possible. But just out of curious,  may I ask your use case for this request ?

**Comment by mdopieralski** [comment]
Hi @raychenfj, it may be useful to create some kind of "Clear" button for example, which will allow to set default value. That's my use case, which actually conducted me to this plugin and issue :-)

PS. Thanks for your amazing job with this plugin !

**Comment by bnfrnz** [comment]
Hi @raychenfj - First, thanks much for this! 
I'd like to +1 the "Clear" button idea. Our use case also demands being able to reset the picker values to null. And I would imagine this to be quite a common case. Thanks for considering...

**Comment by plaidfox** [comment]
@raychenfj This plugin is awesome. I agree with bnfrnz and mdopieralski. I'd love to have a quick clear button for users to reset their multi-picker.

Thanks!

**Comment by raychenfj** [comment]
Accepted, will try to add a clear/reset buttton in my coming weekend.

Thanks.

**Comment by raychenfj** [comment]
This feature is released in version 2.1.1, thanks.
