### ISSUE TITLE
ionic3 and angular4.0 bug

### ISSUE THREAD

**Issue by HonLuk** [raychenfj/ion-multi-picker#42]
got error:ERROR TypeError: Cannot read property '_cols' of undefined;
and animate dont work now.when change parentColumns,childColumns crowded together .need click to normal.
ionic 3.0.1
angular4.0.0

**Comment by TonyZhou2017** [comment]
Hi, I have the same error on ionic 3.0.1.

**Comment by TonyZhou2017** [comment]
Thanks for your quick solution, really nice, it works now.

**Comment by raychenfj** [comment]
2.0.0 released, should support ionic3.

**Comment by HonLuk** [comment]
@raychenfj thanks!I will try later.3.0.1 have some bug.i dont want to update now.but u can close this issue now. thanks so much~
