### ISSUE TITLE
ngModelChange does get updated model.

### ISSUE THREAD

**Issue by alwaysprep** [raychenfj/ion-multi-picker#44]
`<ion-item>`
`<ion-label> Default Value</ion-label>`
   `    <ion-multi-picker`
     `    item-content`
     `   [ngModel]="picker"`
     `   id="picker"`
     `   [multiPickerColumns]="dependentColumns"`
     `   (ngModelChange)="onChange(picker)"`
   `    >`
  `</ion-multi-picker>`
 `</ion-item>`

onChange method always get the initial value of picker model.

**Comment by raychenfj** [comment]
@alwaysprep 

I've googled for a while but found little info about how to implement this `ngModelChange`.

So do you happen to know how to implement this `ngModelChange` on a custom component ?

**Comment by jayordway** [comment]
Try passing the event:

 (ngModelChange)="onModelChange($event)"

**Comment by raychenfj** [comment]
ngModelChange event is fired when you click done. 
and the $event will be the current value of the picker.
