### ISSUE TITLE
how to set up the placeholder？

### ISSUE THREAD

**Issue by ruoruostar** [raychenfj/ion-multi-picker#45]
In ion-list,I use ion-multi-picker,also ion-input.ion-input can set up placeholder，but ion-multi-picker.so that the right of the content is not unified in some line.

在ion-list中使用了ion-multi-picker标签和ion-input标签，ion-input可以设置占位文字，但是ion-multi-picker不可以设置。这样导致了表格的右边有一些行是不统一的。

**Comment by ruoruostar** [comment]
> [``](

url

)

**Comment by raychenfj** [comment]
@ruoruostar 

Sorry for my late response.

It is very similiar to the official datetime componentit and it doesn't support placeholder at this point.

If you can provide a screenshot and explain what you expect, I may consider add a new feature to support placeholder.

**Comment by raychenfj** [comment]
Add placeholder in new version 2.0.2
