### ISSUE TITLE
can't build with prod with ionic3.1.1 lazy load

### ISSUE THREAD

**Issue by HonLuk** [raychenfj/ion-multi-picker#49]
follow this [ionic-3-lazy-loading](https://ionicacademy.com/ionic-3-lazy-loading/) rebuild my project.
[see detail ](https://forum.ionicframework.com/t/ionic3-lazy-loading-with-plugins-module/89772)
dont know where import this plugin when use lazy load.

**Comment by raychenfj** [comment]
Version 2.1.0 is released to fix this.
