### ISSUE TITLE
 Cannot read property '1' of undefined  at multi-picker.js:157

### ISSUE THREAD

**Issue by vvu2014** [raychenfj/ion-multi-picker#50]
ERROR TypeError: Cannot read property '1' of undefined   at multi-picker.js:157

**Comment by raychenfj** [comment]
Can you provide your input data used to setup the columns so that I can reproduce the issuse and debug ?

**Comment by GGwujun** [comment]
![image](https://cloud.githubusercontent.com/assets/17949342/26273241/15d230d6-3d5e-11e7-986e-9dccaf0fd080.png)

**Comment by 93xiaoliumang** [comment]
hello , I also have this problem, I follow your step, and data all yours ,include 'city.json' , but still not work.  . can you fixed the issue ? thanks @raychenfj

**Comment by eanfs** [comment]
i also have this problem

**Comment by raychenfj** [comment]
Thanks guys, thanks for your feedback,  will spend some time during this weekend to fix it.

**Comment by raychenfj** [comment]
Fixed in new version 2.0.2.
