### ISSUE TITLE
设置的ngModel第一次的值不会显示

### ISSUE THREAD

**Issue by DaiHuaXieHuaKai** [raychenfj/ion-multi-picker#53]
当我使用ngModel的时候设置default为“请选择”在页面上并不会显示，然后我修改了源码增加了placeholderText参数，实现了我的需求，但是后来我加上了separator后，页面显示的是value的值而不是text值，该如何解决呢？

**Comment by raychenfj** [comment]
Intially, default value is not designed for placeholder text, its value from your input column

Currently it doesn't supprot placeholder, sorry :(

Can't give any suggestion withour going throught your code first

**Comment by raychenfj** [comment]
Add placeholder in new version 2.0.2
