### ISSUE TITLE
Personnalisée bouton 'Done' and 'Cancel'

### ISSUE THREAD

**Issue by Kayl51** [raychenfj/ion-multi-picker#54]
Hello

A suggestion for a future release would be to customize the 'Done' and 'Cancel'

Currently I modify the file I modify the file 'multi-picker.js'

Can be another solution if not?

Sorry for my english

Kayl

**Comment by raychenfj** [comment]
@Kayl51 
so what kinds of customization do you mean ?

If you only want to change its style, you can override its css

or you want to have some hooks or events fired when click cancel or done button ?

**Comment by Kayl51** [comment]
Juste changer le label 'Cancel' and 'Done' pour le language de l'application

Pour une app Française par exemple
'Cancel' vers 'Annuler'

**Comment by raychenfj** [comment]
There are two input attribute you can use to change the default text.
Guess I forget to metion them in the doc.

```typescript
/**
 * @input {string} The text to display on the picker's cancel button. Default: `Cancel`.
 */
@Input() cancelText: string = 'Cancel';

/**
 * @input {string} The text to display on the picker's "Done" button. Default: `Done`.
 */
@Input() doneText: string = 'Done';
```
