### ISSUE TITLE
Failed to load multi-picker.html

### ISSUE THREAD

**Issue by liugogal** [raychenfj/ion-multi-picker#56]
I use the new version! But it has the error

Failed to load multi-picker.html

**Comment by CloverEc** [comment]
me too

**Comment by CloverEc** [comment]
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : not installed
    npm        : 5.0.3

**Comment by raychenfj** [comment]
Sorry guys, my bad :(,  forget to check the build process when I change to use a html template.
Please use previous version for now, new version is on the way to fix this critical issuse.

**Comment by raychenfj** [comment]
2.0.3 is released to fix this critical issuse.
