### ISSUE TITLE
Add a wrapper/class names for each column's output

### ISSUE THREAD

**Issue by fayecheah** [raychenfj/ion-multi-picker#59]
Hi all,

Is it possible to add a wrapper to each column's output? For example, now it's giving me

`<div class="multi-picker-text">Col1Value Col2Value Col3Value</div>`

I would like to have each column to be wrapped with a `<span>`:
`<div class="multi-picker-text"><span>Col1Value</span> <span>Col2Value</span> <span>Col3Value</span></div>`

or even better, with class name `<span class="Col1ClassName">..</span> <span class="Col2ClassName">..</span>.. ` if possible.

Appreciate any help!

Thanks.

**Comment by raychenfj** [comment]
@fayecheah ,
I use the ionic official picker component, so I can't modify it myself. 
I guess If you want to modify css style, you can override css directly.
