### ISSUE TITLE
prefix selector

### ISSUE THREAD

**Issue by JosephSKh** [raychenfj/ion-multi-picker#63]
Hello, can you prefix the selector of the component as so many plugins use the same selector name and that causes issues?
thanks

**Comment by raychenfj** [comment]
Hi @JosephSKh,

I'm afraid this will be a breaking change, will break many others' build if the selecor name is changed. 

Probably you should just fork one, and then change the selector.

**Comment by JosephSKh** [comment]
@raychenfj thank you for your response, yes actually that's what I've done
thanks man
