### ISSUE TITLE
Align with datetime picker style

### ISSUE THREAD

**Issue by jasonz1987** [raychenfj/ion-multi-picker#67]
great plugin, but you can add these css padding for align with datetime picker .

```
ion-multi-picker {
padding: 11px 8px 11px 16px;
}
```

before 

![image](https://user-images.githubusercontent.com/7090036/30464195-b1a6333a-9a02-11e7-9209-e01a53ad8776.png)

after 

![image](https://user-images.githubusercontent.com/7090036/30464181-9afb0b56-9a02-11e7-83e4-e56546b72c4e.png)

**Comment by raychenfj** [comment]
Hi @jasonz1987 

Thanks for your advice.
I will check the style of datetime picker, make sure we are same.

**Comment by raychenfj** [comment]
Fixed in version 2.1.2.
