### ISSUE TITLE
How to get selected value and text

### ISSUE THREAD

**Issue by zhiwo** [raychenfj/ion-multi-picker#69]
如标题，请教怎么才能得到页面中的文本和值

**Comment by raychenfj** [comment]
@zhiwo 

通过ngModel绑定变量后可以获得选中的值，如果多选的话值会以 separator 指定的字符分隔，默认是空格。

组件本身并不返回选中的文本，需要获取文本的话，可以通过值去你传入的 multiPickerColumns 参数中查对应的文本

You can use ngModel to bind a variable to this component, then you can get the selected value via that variable.

If you need the text, then you can use the selected value to find its corresponding text in your column options.

**Comment by zhiwo** [comment]
但是通过后台获取文本的话，没有办法改变文本显示的值

**Comment by raychenfj** [comment]
Shouldn't discuss too much of your business logic or implementation detail here.

As long as your provide a correct input, this component should work as expect. 
If not, report a bug. 😊
