### ISSUE TITLE
Can i call picker open directly

### ISSUE THREAD

**Issue by zuo305** [raychenfj/ion-multi-picker#72]
Hi. Thank for open source this lib. It's very cool stuff. And one more request. Can i call picker open directly? Just using <ion-multi-picker item-content [multiPickerColumns]="dependentColumns"></ion-multi-picker> and call MultiPicker.open() directly.

不好意思，我可以不可以 直接 call picker open,不需要 嵌套 ion-item 和 label.我有自己的一些东西要显示。

**Comment by raychenfj** [comment]
I guess you can try yourself, but there is no guarantee.

You can create a new issue if anything goes wrong.
