### ISSUE TITLE
what？ Why does forEach have no definition? Thank you for the answer

### ISSUE THREAD

**Issue by chengkai3396** [raychenfj/ion-multi-picker#83]
![qq 20180416161127](https://user-images.githubusercontent.com/24379114/38797392-e1803ab6-4190-11e8-9711-5e4f03e57104.png)
 
what？ Why does forEach have no definition? Thank you for the answer

**Comment by MatrixMatt249** [comment]
Most likely is happening because you aren't providing the multiPickerColumns with an array of type MultiPickerColumn. 
But i would need to see an example of what you are trying to do to provide a better answer.

**Comment by raychenfj** [comment]
Closed since no further discussion.
